export const data = [
  {
    title: 'Vehicle',
    icon: 'drive_eta',
    gradientColor1: '#bcc0cc',
    gradientColor2: '#e2e4e9',
    stringArray: [
      'Aircraft',
      'Automotive Items & Parts',
      'Boats & Watercraft',
      'Cars',
      'Classic Cars',
      'Commercial Trucks',
      'Motorcycles',
      'Off Road Vehicles',
      'RV & Motorhomes',
      'SUVs',
      'Vans',
      'Vehicle Wanted',
      'Utility & Work Trailers',
    ],
  },
  {
    title: 'Services',
    icon: 'headset_mic',
    gradientColor1: '#fade60',
    gradientColor2: '#fdf3c5',
    stringArray: [
      'Automotive Services',
      'Beauty & Salon Services',
      'Caregivers & Baby Sitting',
      'Cleaning Services',
      'Construction & Remodeling',
      'Real Estate Services',
      'Training & Education Services',
      'Web Design & Tech',
      'Wedding & Photography',
      'Moving & Storage',
      'Financial Services',
      'Health & Wellness',
      'Home Services',
      'Lawn & Garden Services',
      'Marketing Services',
    ],
  },
  {
    title: 'Items For Sale',
    icon: 'card_travel',
    gradientColor1: '#f2f2f2',
    gradientColor2: '#fbfbfb',
    stringArray: [
      'Appliances',
      'Art & Crafts',
      'Automotive Items & Parts',
      'Cell Phones',
      'Collectibles',
      'Jewelery',
      'Kids Stuff',
      'Lawn & Garden',
      'Mattresses',
      'Music & Cds',
      'Music & DVDs',
      'Tools',
      'Tickets',
      'Office & Business',
      'Sports Equipment',
      'Tickets',
      'Toys & Games',
      'Kids Stuff',
      'Lawn & Garden',
      'Mattresses',
      'Music & Cds',
      'Music & DVDs',
    ],
  },
  {
    title: 'Jobs',
    icon: 'work',
    gradientColor1: '#f78787',
    gradientColor2: '#fde5e5',
    stringArray: [
      'Accounting & Bookkeeping Jobs',
      'Business Opportunities',
      'Cleaning Jobs',
      'Construction Work',
      'Creative Jobs',
      'Educational Jobs',
      'Financial & Real Estate Jobs',
      'Internships',
      'IT Jobs',
      'Labor Jobs',
      'Legal Jobs',
      'Management Jobs',
      'Marketing Jobs',
      'Medical Jobs',
      'Office Jobs',
      'Other Jobs',
    ],
  },
  {
    title: 'Pets',
    icon: 'pets',
    gradientColor1: '#f2f2f2',
    gradientColor2: '#fbfbfb',
    stringArray: [
      'Birds',
      'Cats',
      'Dogs',
      'Fish & Reptile Pets',
      'Free Pets to Good Home',
      'Horses',
      'Livestock',
      'Other Pets',
      'Pet Services & Stores',
      'Pet Supplies',
      'Pets Lost & Found',
    ],
  },
  {
    title: 'Real Estate',
    icon: 'business',
    gradientColor1: '#bcc0cc',
    gradientColor2: '#e2e4e9',
    stringArray: [
      'Commercial Real Estate',
      'Condos For Sale',
      'Farms & Ranches',
      'Homes For Sale',
      'Land For Sale',
      'Manufactured Homes',
      'Other Real Estate',
      'Real Estate Services',
      'Time Shares',
      'Townhomes For Sale',
      'Vacation Homes',
    ],
  },
  {
    title: 'For Rent',
    icon: 'home',
    gradientColor1: '#f78787',
    gradientColor2: '#fde5e5',
    stringArray: [
      'Apartments For Rent',
      'Commercial Lease',
      'Condos For Rent',
      'Homes For Rent',
      'Roommates',
      'Townhomes For Rent',
      'Vacation Homes',
    ],
  },
  {
    title: 'Community',
    icon: 'people',
    gradientColor1: '#fade60',
    gradientColor2: '#fdf3c5',
    stringArray: [
      'Announcements',
      'Car Pool',
      'Churches',
      'Free Stuff',
      'Garage Sales',
      'General Entertainment',
      'Items Wanted',
      'Lost & Found',
      'Musicians & Bands',
      'Volunteers',
    ],
  },
];
